Q1: Create the following training datasets from the optdigits.tra set: 
X25: Randomly chosen N=25 instances from each class. 
X100:  Randomly chosen N=100 instances from each class.

In [99]:
import numpy as np
import pandas as pd
from pandas import DataFrame, read_csv, to_numeric
from sklearn import cluster
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
import math

In [100]:
# setting header = None here to get the column names as in order starting from 0

train_data = (pd.read_csv('/media/anuja/study/Anuja/MS/githubLibraries/MLprojects/Assignment3/optdigits.tra',
                         sep=",", header = None))
train_data

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,64
0,0,1,6,15,12,1,0,0,0,7,...,0,0,0,6,14,7,1,0,0,0
1,0,0,10,16,6,0,0,0,0,7,...,0,0,0,10,16,15,3,0,0,0
2,0,0,8,15,16,13,0,0,0,1,...,0,0,0,9,14,0,0,0,0,7
3,0,0,0,3,11,16,0,0,0,0,...,0,0,0,0,1,15,2,0,0,4
4,0,0,5,14,4,0,0,0,0,0,...,0,0,0,4,12,14,7,0,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3818,0,0,5,13,11,2,0,0,0,2,...,0,0,0,8,13,15,10,1,0,9
3819,0,0,0,1,12,1,0,0,0,0,...,0,0,0,0,4,9,0,0,0,4
3820,0,0,3,15,0,0,0,0,0,0,...,0,0,0,4,14,16,9,0,0,6
3821,0,0,6,16,2,0,0,0,0,0,...,0,0,0,5,16,16,16,5,0,6
3822,0,0,2,15,16,13,1,0,0,0,...,0,0,0,4,14,1,0,0,0,7

In [101]:
# create dataset of 25 instances of each class and 100 instances of each class

classes = 10
X25_train = train_data[train_data[64] == 0].sample(25)
X100_train = train_data[train_data[64] == 0].sample(100)
#print(X25_train)
# print(X100_train)
for i in range(1,classes,1):

    X25_train = X25_train.append(train_data[train_data[64] == i].sample(25), ignore_index = True)
    X100_train = X100_train.append(train_data[train_data[64] == i].sample(100), ignore_index= True)

# with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can
# be specified also
#     display(X25_train)

Q4: Multilayer Perceptrons: classification 
Use library sklearn.neural_network.MLPClassifier. 
For the neural network (MLP) determine the value of the best hidden_layer_sizes (experiment with 1 and 2 hidden layers and 2, 5, 10 hidden units in each layer) that results in the best test error for each of the training data sets you created.