In [39]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
import statsmodels.api as sm
from statsmodels.formula.api import ols
from scipy.stats import ttest_ind
import scipy.stats as stats
from ipykernel import kernelapp as app
import sys
import math

In [40]:
traindf = pd.read_csv(r"/Users/STSC/Desktop/cs697a/hw2/optdigits_69_N200.tra",header=None)
train_df = pd.read_csv(r"/Users/STSC/Desktop/cs697a/hw2/optdigits_69_N200.tra",header=None)
testdf = pd.read_csv(r'/Users/STSC/Desktop/cs697a/hw2/optdigits_69.tes',header=None)
test_df = pd.read_csv(r'/Users/STSC/Desktop/cs697a/hw2/optdigits_69.tes',header=None)
train_df = traindf.drop(traindf.columns[64],axis=1)
test_df = testdf.drop(testdf.columns[64],axis=1)

In [41]:
#Q1
class6 = train_df[:100]
test6 = test_df[:180]
class9 = train_df[100:]
test9 = test_df[180:]
testerrors = {}
trainerrors = {}
class6mean = []
class9mean = []
class6std = []
class9std = []
m = 64
for i in range(m):
    temp1 = np.std(class6[i])
    class6std.append(temp1)
    temp2 = np.std(class9[i])
    class9std.append(temp2)
    temp3 = np.mean(class6[i])
    class6mean.append(temp3)
    temp4 = np.mean(class9[i])
    class9mean.append(temp4)

In [42]:
best = {}
for col in range(m):
    errors = 0
    for i in range(200):
        if (class6std[col] != 0):
             g6 = -(np.log(2*np.pi)/2) - np.log(class6std[col]) - ((traindf[col][i]-class6mean[col])**2)/(2*((class6std[col])**2)) + np.log(0.5)
        else:
            continue

        if (class9std[col] != 0):
            g9 = -(np.log(2*np.pi)/2) - np.log(class9std[col]) - ((traindf[col][i]-class9mean[col])**2)/(2*((class9std[col])**2)) + np.log(0.5)
        else:
            continue
        if g6 < g9:
            if i < 100:
                errors += 1
        else:
            if i >= 100:
                errors += 1
                
    if errors != 0:
        trainerrors[col] = errors
print("Training errors: ", trainerrors)
print("\n")

for col in range(m):
    errors = 0
    for i in range(361):
        if (class6std[col] != 0):
             t6 = -(np.log(2*np.pi)/2) - np.log(class6std[col]) - ((testdf[col][i]-class6mean[col])**2)/(2*((class6std[col])**2)) + np.log(0.5)
        else:
            continue

        if (class9std[col] != 0):
            t9 = -(np.log(2*np.pi)/2) - np.log(class9std[col]) - ((testdf[col][i]-class9mean[col])**2)/(2*((class9std[col])**2)) + np.log(0.5)
        else:
            continue
        if t6 < t9:
            if i < 180:
                errors += 1
        else:
            if i >= 180:
                errors += 1
                
    if errors != 0:
        testerrors[col] = errors
print("Test errors: ", testerrors)
print("\n")
best = sorted(testerrors.items(), key=lambda k:k[1])
best = best[:10]
print("Best 10 features are: ", best)

Training errors:  {2: 63, 3: 65, 4: 68, 5: 63, 9: 62, 10: 59, 11: 78, 12: 58, 13: 20, 17: 55, 18: 91, 19: 77, 20: 37, 25: 94, 26: 78, 27: 74, 28: 31, 29: 4, 30: 19, 33: 43, 34: 19, 35: 51, 36: 58, 37: 74, 38: 72, 41: 57, 42: 1, 43: 19, 44: 89, 45: 90, 46: 54, 49: 98, 50: 45, 51: 40, 52: 74, 53: 98, 54: 35, 55: 80, 57: 93, 58: 62, 59: 53, 60: 72, 61: 52, 62: 50, 63: 88}


Test errors:  {2: 81, 3: 137, 4: 151, 5: 110, 9: 94, 10: 80, 11: 86, 12: 127, 13: 30, 17: 109, 18: 185, 19: 130, 20: 55, 25: 198, 26: 125, 27: 120, 28: 58, 29: 30, 30: 49, 33: 70, 34: 31, 35: 75, 36: 91, 37: 162, 38: 135, 41: 85, 42: 5, 43: 32, 44: 135, 45: 184, 46: 125, 49: 162, 50: 102, 51: 61, 52: 167, 53: 176, 54: 97, 55: 162, 57: 167, 58: 84, 59: 121, 60: 148, 61: 113, 62: 132, 63: 177}


Best 10 features are:  [(42, 5), (13, 30), (29, 30), (34, 31), (43, 32), (30, 49), (20, 55), (28, 58), (51, 61), (33, 70)]

In [43]:
#Q2
class_6,test_6,class6mean,class6std,class9mean,class9std,class_9,test_9,testerrors,trainerrors = [],[],[],[],[],[],[],[],[],[]
for i in range(m):
    temp1 = np.std(class6[i])
    if temp1 == 0:
        train_df = train_df.drop(i,axis = 1)
        class6 = class6.drop(i,axis = 1)
        class9 = class9.drop(i,axis = 1)
        test_df = test_df.drop(i, axis = 1)
        test6 = test6.drop(i,axis = 1)
        test9 = test9.drop(i,axis = 1)
        continue
    class6std.append(temp1)
    temp2 = np.mean(class6[i])
    class6mean.append(temp2)
    
    temp3 = np.std(class9[i])
    if temp3 == 0:
        train_df = train_df.drop(i,axis = 1)
        class6 = class6.drop(i,axis = 1)
        class9 = class9.drop(i,axis = 1)
        test_df = test_df.drop(i, axis = 1)
        test6 = test6.drop(i,axis = 1)
        test9 = test9.drop(i,axis = 1)
        continue
    class9std.append(temp3)
    temp4 = np.mean(class9[i])
    class9mean.append(temp4)

train = np.array(train_df)
test = np.array(test_df)
class_6 = np.array(class6)
class_9 = np.array(class9)
test_6 = np.array(test6)
test_9 = np.array(test9)
class6mean.remove(0.17)

In [44]:
six,nine,p = np.cov(class6.T), np.cov(class9.T), 1/2
z1,z2 = np.array(six), np.array(nine)
m1, m2 = np.linalg.inv(six), np.linalg.inv(nine)
A1,a1 = -1/2*(m1), m1.dot(class6mean)
L1 = 1/2*(np.transpose(class6mean).dot(m1.dot(class6mean))) - 1/2*(math.log(np.linalg.det(six))+math.log(p))
A2,a2 = -1/2*(m2), m2.dot(class9mean)
L2 = 1/2*(np.transpose(class9mean).dot(m2.dot(class9mean))) - 1/2*(math.log(np.linalg.det(nine))+math.log(p))
traintp,traintn,trainfp,trainfn,testtp,testtn,testfp,testfn = 0,0,0,0,0,0,0,0
for i,value in enumerate(train):
    g6 = ((value.T).dot(A1)).dot(value) + (a1.T).dot(value)+L1
    g9 = ((value.T).dot(A2)).dot(value) + (a2.T).dot(value)+L2    
    
    if g6 < g9:
        ptrain = 9
    else:
        ptrain = 6
    
    if ptrain == traindf[m][i]:
        if ptrain == 6:
            traintp += 1
        else:
            traintn += 1
    else:
        if traindf[m][i] == 6 and ptrain == 9:
            trainfn += 1
        else:
            trainfp += 1
print("tp,tn,fp,fn: ",traintp, traintn , trainfp, trainfn)

for i,value in enumerate(test):
    t6 = ((value.T).dot(A1)).dot(value) + (a1.T).dot(value)+L1
    t9 = ((value.T).dot(A2)).dot(value) + (a2.T).dot(value)+L2    
    
    if t6 < t9:
        ptrain = 9
    else:
        ptrain = 6
    
    if ptrain == testdf[m][i]:
        if ptrain == 6:
            testtp += 1
        else:
            testtn += 1
    else:
        if testdf[m][i] == 6 and ptrain == 9:
            testfn += 1
        else:
            testfp += 1
print("tp,tn,fp,fn: ",testtp, testtn , testfp, testfn)

tp,tn,fp,fn:  100 100 0 0
tp,tn,fp,fn:  179 177 3 2

In [45]:
#3
common_covm=p*z1+p*z2
array_common_covm=np.array(common_covm)
inv_of_common_covm=np.linalg.inv(array_common_covm)
traintruepositive,traintruenegative,trainfalsepositive,trainfalsenegative,testtruepositive,testtruenegative,testfalsepositive,testfalsenegative=0,0,0,0,0,0,0,0


w6=inv_of_common_covm.dot(class6mean)

w60=-1/2*(np.transpose(class6mean)).dot(inv_of_common_covm).dot(class6mean) + math.log(p)

w9=inv_of_common_covm.dot(class9mean)

w90=-1/2*(np.transpose(class9mean)).dot(inv_of_common_covm).dot(class9mean) + math.log(p)


for i,value in enumerate(train):
    
    g_for_6=(w6.T).dot(value)+w60
    
    g_for_9=(w9.T).dot(value)+w90
    
    if(g_for_6 < g_for_9):
        pred=9
    else:
        pred=6
    
    
    if pred==traindf[m][i]:
        if pred==6:
            traintruepositive+=1
        else:
            traintruenegative+=1
    else:
        if(pred==9 and traindf[m][i]==6):
            trainfalsepositive+=1
        else:
            trainfalsenegative+=1
    
    
print("truepositive,truenegative,falsepositive,falsenegative: ",traintruepositive,traintruenegative,trainfalsepositive,trainfalsenegative)

for i,value in enumerate(test):
    
    g_for_6=(w6.T).dot(value)+w60
    
    g_for_9=(w9.T).dot(value)+w90

    if(g_for_6 < g_for_9):
        pred=9
    else:
        pred=6
    
    
    if pred==testdf[m][i]:
        if pred==6:
            testtruepositive+=1
        else:
            testtruenegative+=1
    else:
        if(pred==9 and traindf[m][i]==6):
            testfalsepositive+=1
        else:
            testfalsenegative+=1
    
    
print("truepositive,truenegative,falsepositive,falsenegative: ",testtruepositive,testtruenegative,testfalsepositive,testfalsenegative)

training_error_q3 = (trainfalsepositive + trainfalsenegative)/(trainfalsepositive + trainfalsenegative + traintruepositive + traintruenegative)
testing_error_q3= (testfalsepositive +testfalsenegative)/(testfalsepositive + testfalsenegative + testtruepositive + testtruenegative)

print("\nTraining Error using confusion matrix: ", training_error_q3)
print("\nTesting Error using confusion matrix: ", testing_error_q3)

truepositive,truenegative,falsepositive,falsenegative:  100 100 0 0
truepositive,truenegative,falsepositive,falsenegative:  180 180 0 1

Training Error using confusion matrix:  0.0

Testing Error using confusion matrix:  0.002770083102493075

In [50]:
#4
testdf_1 = pd.read_csv(r'/Users/STSC/Desktop/cs697a/hw2/optdigits_69.tes',header=None)
Top_Best_data_set = testdf_1[[42,29,10,13,28,34,35,36,51,54,64]].copy()
test_df_4=np.array(Top_Best_data_set)

Top_Best_data_set

     42  29  10  13  28  34  35  36  51  54  64
0    13   0   5   0   0  15  12   7  16   8   6
1    15   0   0   0   2   7  16  16  14  16   6
2    16   0   8   2   1  16  14   5  16  12   6
3    13   0   1   0   5  15  16  15  16   9   6
4    16   0  11   0   0  16  15   8  16  14   6
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
356   0  16  16  16  15   0   4   4   9   7   9
357   0  15  15  16  16   0   4  10   8   0   9
358   0  16  16  16  13   0   0   8   6   6   9
359   0  16  16  16  16   0   4   4   7   4   9
360   0  16  14  15   7   5  14  14   7   2   9

[361 rows x 11 columns]

In [51]:
Top_Best_data=Top_Best_data_set.drop(testdf.columns[64],axis=1)
Top_Best_data

     42  29  10  13  28  34  35  36  51  54
0    13   0   5   0   0  15  12   7  16   8
1    15   0   0   0   2   7  16  16  14  16
2    16   0   8   2   1  16  14   5  16  12
3    13   0   1   0   5  15  16  15  16   9
4    16   0  11   0   0  16  15   8  16  14
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
356   0  16  16  16  15   0   4   4   9   7
357   0  15  15  16  16   0   4  10   8   0
358   0  16  16  16  13   0   0   8   6   6
359   0  16  16  16  16   0   4   4   7   4
360   0  16  14  15   7   5  14  14   7   2

[361 rows x 10 columns]

In [52]:
Test6_4=Top_Best_data[:180]
Test9_4=Top_Best_data[180:]

mean_64,mean_94 = np.mean(Test6_4),np.mean(Test9_4)     
testerrors = {}

cov_6_q4=np.cov(Test6_4.T)
cov_9_q4=np.cov(Test9_4.T)
s1,s2=np.array(cov_6_q4),np.array(cov_9_q4)

inv_cov_6_q4=np.linalg.inv(cov_6_q4)
inv_cov_9_q4=np.linalg.inv(cov_9_q4)

testtruepositive_q4,testtruenegative_q4,testfalsepositive_q4,testfalsenegative_q4=0,0,0,0


N6,n6=-1/2*(inv_cov_6_q4), inv_cov_6_q4.dot(mean_64)

F6=1/2*(np.transpose(mean_64).dot(inv_cov_6_q4.dot(mean_64)))-1/2*(math.log(np.linalg.det(cov_6_q4)))+math.log(p)


N9,n9=-1/2*(inv_cov_9_q4),inv_cov_9_q4.dot(mean_94)

F9=1/2*(np.transpose(mean_94).dot(inv_cov_9_q4.dot(mean_94)))-1/2*(math.log(np.linalg.det(cov_9_q4)))+math.log(p)


for i, value in enumerate(test_df_4):
    g6 = ((value.T).dot(N6)).dot(value)+(n6.T).dot(value) +F6
    g9 = ((value.T).dot(N9)).dot(value)+(n9.T).dot(value) +F9
    if g6 < g9:
        pred_4 = 9
    else:
        pred_4 = 6
    if pred_4 ==testdf_1[m][i]:
        if pred_ == 6:
            testtruepositive_q4 += 1
        else:
            testtruenegative_q4 +=1
    else:
        if testdf_1[m][i] == 6 and pred_4 == 9:
            testfalsenegative_q4 += 1
        else:
            testfalsepositive_q4 += 1
print("Test of top best 10 features with confusion matrix is truepositive,truenegative,falsepositive,falsenegative: ",testtruepositive_q4,testtruenegative_q4,testfalsepositive_q4,testfalsenegative_q4)

ValueError: shapes (11,) and (10,10) not aligned: 11 (dim 0) != 10 (dim 0)