Q1: Create the following training datasets from the optdigits.tra set: 
X25: Randomly chosen N=25 instances from each class. 
X100:  Randomly chosen N=100 instances from each class.

In [7]:
import numpy as np
import pandas as pd
from pandas import DataFrame, read_csv, to_numeric
from sklearn import cluster
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
import math

In [8]:
# setting header = None here to get the column names as in order starting from 0

train_data = (pd.read_csv('/media/anuja/study/Anuja/MS/githubLibraries/MLprojects/Assignment3/optdigits.tra',
                         sep=",", header = None))
train_data

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,64
0,0,1,6,15,12,1,0,0,0,7,...,0,0,0,6,14,7,1,0,0,0
1,0,0,10,16,6,0,0,0,0,7,...,0,0,0,10,16,15,3,0,0,0
2,0,0,8,15,16,13,0,0,0,1,...,0,0,0,9,14,0,0,0,0,7
3,0,0,0,3,11,16,0,0,0,0,...,0,0,0,0,1,15,2,0,0,4
4,0,0,5,14,4,0,0,0,0,0,...,0,0,0,4,12,14,7,0,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3818,0,0,5,13,11,2,0,0,0,2,...,0,0,0,8,13,15,10,1,0,9
3819,0,0,0,1,12,1,0,0,0,0,...,0,0,0,0,4,9,0,0,0,4
3820,0,0,3,15,0,0,0,0,0,0,...,0,0,0,4,14,16,9,0,0,6
3821,0,0,6,16,2,0,0,0,0,0,...,0,0,0,5,16,16,16,5,0,6
3822,0,0,2,15,16,13,1,0,0,0,...,0,0,0,4,14,1,0,0,0,7

In [9]:

test_data = (pd.read_csv('/media/anuja/study/Anuja/MS/githubLibraries/MLprojects/Assignment3/optdigits.tes',
                         sep=",", header = None))
test_data

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,64
0,0,0,5,13,9,1,0,0,0,0,...,0,0,0,6,13,10,0,0,0,0
1,0,0,0,12,13,5,0,0,0,0,...,0,0,0,0,11,16,10,0,0,1
2,0,0,0,4,15,12,0,0,0,0,...,0,0,0,0,3,11,16,9,0,2
3,0,0,7,15,13,1,0,0,0,8,...,0,0,0,7,13,13,9,0,0,3
4,0,0,0,1,11,0,0,0,0,0,...,0,0,0,0,2,16,4,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,0,0,4,10,13,6,0,0,0,1,...,0,0,0,2,14,15,9,0,0,9
1793,0,0,6,16,13,11,1,0,0,0,...,0,0,0,6,16,14,6,0,0,0
1794,0,0,1,11,15,1,0,0,0,0,...,0,0,0,2,9,13,6,0,0,8
1795,0,0,2,10,7,0,0,0,0,0,...,0,0,0,5,12,16,12,0,0,9
1796,0,0,10,14,8,1,0,0,0,2,...,0,0,1,8,12,14,12,1,0,8

In [10]:
# create dataset of 25 instances of each class and 100 instances of each class

classes = 10
X25_train = train_data[train_data[64] == 0].sample(25)
X100_train = train_data[train_data[64] == 0].sample(100)
#print(X25_train)
# print(X100_train)
for i in range(1,classes,1):

    X25_train = X25_train.append(train_data[train_data[64] == i].sample(25), ignore_index = True)
    X100_train = X100_train.append(train_data[train_data[64] == i].sample(100), ignore_index= True)

# with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can
# be specified also
#     display(X25_train)

Q4: Multilayer Perceptrons: classification 
Use library sklearn.neural_network.MLPClassifier. 
For the neural network (MLP) determine the value of the best hidden_layer_sizes (experiment with 1 and 2 hidden layers and 2, 5, 10 hidden units in each layer) that results in the best test error for each of the training data sets you created.

In [11]:
# get the X_train and Y_train

X_train_25 = X25_train.iloc[:,0:64]
Y_train_25 = X25_train.iloc[:,64];  #classification or label column

X_train_100 = X100_train.iloc[:,0:64]
Y_train_100 = X100_train.iloc[:,64];

# X_test = test_data.iloc[:,0:64]
# Y_test = test_data.iloc[:,64]
X_test = test_data[test_data.columns[0:64]]
Y_test = test_data[test_data.columns[64]]

print(X_test.shape)
print(Y_test.shape)
print(type(X_test))
print(type(Y_test))

(1797, 64)
(1797,)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [15]:
from sklearn.neural_network import MLPClassifier

# experiment with 1 and 2 hidden layers and 2, 5, 10 hidden units in each layer
layers = [1,2]
hidden_units = [2,5,10]
trainError_25_layer1 = []
testError_25_layer1 =[]
trainError_100_layer1 = []
testError_100_layer1 =[]

trainError_25_layer2 = []
testError_25_layer2 =[]
trainError_100_layer2 = []
testError_100_layer2 =[]
index = []
columns = ['Training Error','Testing Error']


# for layer 1
layers = 1
for units in hidden_units:

        clf1 = MLPClassifier( alpha=1e-5,max_iter=10000, hidden_layer_sizes=(units,layers), random_state=1)
        clf1.fit(X_train_25, Y_train_25)
        trainError_25_layer1.append(1 - clf1.score((X_train_25),(Y_train_25)))
        testError_25_layer1.append(1 - clf1.score(X_test,Y_test))
        
        clf2 = MLPClassifier(alpha=1e-5, max_iter=10000,hidden_layer_sizes=(units,layers), random_state=1)
        clf2.fit(X_train_100, Y_train_100)
        trainError_100_layer1.append(1 - clf2.score((X_train_100),(Y_train_100)))
        testError_100_layer1.append(1 - clf2.score(X_test,Y_test))
        index.append('Hidden Units = '+str(units))

# for layers 2
layers = 2
for units in hidden_units:

        clf1 = MLPClassifier(alpha=1e-5, max_iter=10000, hidden_layer_sizes=(units,layers), random_state=1)
        clf1.fit(X_train_25, Y_train_25)
        trainError_25_layer2.append(1 - clf1.score((X_train_25),(Y_train_25)))
        testError_25_layer2.append(1 - clf1.score(X_test,Y_test))
        
        clf2 = MLPClassifier(alpha=1e-5, max_iter=10000, hidden_layer_sizes=(units,units), random_state=1)
        clf2.fit(X_train_100, Y_train_100)
        trainError_100_layer2.append(1 - clf2.score((X_train_100),(Y_train_100)))
        testError_100_layer2.append(1 - clf2.score(X_test,Y_test))
        

Error_list_25=[]
Error_list_100=[]
Error_list2_25=[]
Error_list2_100=[]
for i in range(len(trainError_25_layer1)):
    Error_list_25.append([trainError_25_layer1[i],testError_25_layer1[i]])
    Error_list_100.append([trainError_100_layer1[i],testError_100_layer1[i]] )
    
    Error_list2_25.append([trainError_25_layer2[i],testError_25_layer2[i]])
    Error_list2_100.append([trainError_100_layer2[i],testError_100_layer2[i]] )

print("-----Printing results of 25 samples using Multilayer Perceptrons with 1 layer-----")   
df_train_error_25 = pd.DataFrame(Error_list_25,columns=columns,index=index)
print(df_train_error_25.head(20))
print()
print("-----Printing results of 100 samples using Multilayer Perceptrons with 1 layer-----")   
df_train_error_100 = pd.DataFrame(Error_list_100,columns=columns,index=index)
print(df_train_error_100.head(20))
print()
print("-----Printing results of 25 samples using Multilayer Perceptrons with 2 layers-----")   
df2_train_error_25 = pd.DataFrame(Error_list2_25,columns=columns,index=index)
print(df2_train_error_25.head(20))
print()
print("-----Printing results of 100 samples using Multilayer Perceptrons with 2 layers-----")   
df2_train_error_100 = pd.DataFrame(Error_list2_100,columns=columns,index=index)
print(df2_train_error_100.head(20))

-----Printing results of 25 samples using Multilayer Perceptrons with 1 layer-----
                   Training Error  Testing Error
Hidden Units = 2            0.604       0.716750
Hidden Units = 5            0.660       0.757930
Hidden Units = 10           0.692       0.752922

-----Printing results of 100 samples using Multilayer Perceptrons with 1 layer-----
                   Training Error  Testing Error
Hidden Units = 2            0.737       0.762938
Hidden Units = 5            0.618       0.687257
Hidden Units = 10           0.679       0.722315

-----Printing results of 25 samples using Multilayer Perceptrons with 2 layers-----
                   Training Error  Testing Error
Hidden Units = 2            0.548       0.678353
Hidden Units = 5            0.340       0.508625
Hidden Units = 10           0.380       0.559822

-----Printing results of 100 samples using Multilayer Perceptrons with 2 layers-----
                   Training Error  Testing Error
Hidden Units = 2            0.662       0.695047
Hidden Units = 5            0.034       0.212577
Hidden Units = 10           0.000       0.104619


Q5: Regression for digit completion: regression
Use library sklearn.neural_network.MLPRegressor
Using only the data for class 6 and class 9 in X100 for training,  use the first 48 features as inputs and predict the next 16 features,  i.e. create a neural network with 16 outputs. 
Report the test error (use only the instances from classes 6 and 9).
Which pixels are easier to predict?
(Clarification, each of your models will have the same set of features, namely features 1â€¦48.)

In [ ]:
# creating given dataset with class 6 and class 9 and 48 features
X_class69 = X100_train[X100_train[64] == 6]
X_class69.append(X100_train[X100_train[64] == 9])
X_class69_48 = X_class69.iloc[:,0:48]
X_class69_16 = X_class69.iloc[:,48:64]
print(X_class69_16.shape)
Y_class69 = X_class69.iloc[:,64]
print(Y_class69_16.shape)

In [ ]:
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import make_regression
from sklearn.metrics import mean_squared_error

regr = MLPRegressor(random_state=1, max_iter=200).fit(X_class69_48, Y_class69)
regr.score(X_class69_16[:,0:1], Y_class69)
# for prediction, it should be 16 features but getting error
# testing_error = mean_squared_error(Y_class69, regr.predict(X_class69_16.iloc[:,0]))   

# print(testing_error)